name: Generate PDF resume

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  id-token: write

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    env:
      PDF_FILENAME: ken_esparta_cv.pdf
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build PDF using Makefile
        run: make gen/build

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: ${{ env.PDF_FILENAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload PDF to S3
        run: |
          aws s3 cp ${{ env.PDF_FILENAME }} s3://cdn.kenesparta.dev/cv/ --cache-control "public, max-age=3600"
