name: Generate PDF resume

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    env:
      PDF_FILENAME: ken_esparta_cv.pdf

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v3

      - name: Build PDF using Makefile
        run: make gen/build

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: ${{ env.PDF_FILENAME }}

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Upload PDF to GCS
        run: |
          gsutil cp ${{ env.PDF_FILENAME }} gs://cdn.kenesparta.dev/cv/
          gsutil -m setmeta -h "Cache-Control:public, max-age=3600" gs://cdn.kenesparta.dev/cv/${{ env.PDF_FILENAME }}
